[project]
name = "speedchallenge-master"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "jupyter>=1.1.1",
    "notebook>=7.4.3",
    "opencv-python-headless>=4.11.0.86",
    "pytest>=8.4.0",
    "python-dotenv>=1.1.0",
    "transformers[torch]>=4.52.4",
    "wandb>=0.20.1",
]
